const DIRECTION = {
    NORTH: 'NORTH',
    EAST: 'EAST',
    SOUTH: 'SOUTH',
    WEST: 'WEST'
}

const DIRECTION_CLOCKWISE = [DIRECTION.NORTH, DIRECTION.EAST, DIRECTION.SOUTH, DIRECTION.WEST]

module.exports = { DIRECTION, DIRECTION_CLOCKWISE }